### ISSUE TITLE
Broker error, could not be compiled

### ISSUE THREAD

**Issue by oriolclosa** [centreon/centreon-stream-connector-scripts#1]
Hello! I saw that 4 days ago you updated this repo. I have been trying all morning to use it in my Centreon platform but without success (I only tried the neb one). I actually wrote a Lua script last week and it works although it doesn't use any buffer, it just sends the data as soon as available.

I had several problems with Lua (as I am using 5.3 and this script seems to have been tested for 5.1) and Luarocks as the platform I'm working with is a CentOs. Firt of all, I'm trying this solution as the official InfluxDB connector didn't work (an error with the endpoint, but I guess was not our fault).

The thing is that I get this on the broker log.

``[1530537343] error:   lua: '_PATH_/influxdb-neb.lua' could not be compiled``

Which doesn't happen when I try my version without imports nor buffers. Could be a problem with those modules? I can't really see the error. I've set the logging options to very detailed and enabled all options but nothing else than "could not be compiled" appears. I have also tried to compile manually the script and everything is fine.

Thank-you!

**Comment by bouda1** [comment]
Hi,

Could you execute the command:
cd path-to-the lua-script
lua influxdb-neb.lua

If the script could not be compiled you should have an error.
Please send it here.

Thanks.

**Comment by oriolclosa** [comment]
That's exactly what I've done, nothing prompts, so I guessed there was no compiling errors.

**Comment by bouda1** [comment]
OK, the script compiles with lua but not with broker.
How did you install the lua interpreter on your computer ? influxdb-neb.lua script needs the luasocket library. How did you get it ?

And maybe a stupid remark, I'm a little confused with the error you give:
`error: lua: '_PATH_/influxdb-neb.lua' could not be compiled`
What is this \_PATH\_ thing ? If you installed the script in `/usr/share/centreon-broker/lua/` directory, you
must provide `/usr/share/centreon-broker/lua/influxdb-neb.lua` in the broker configuration. And the error should be something like `/usr/share/centreon-broker/lua/influxdb-neb.lua could not be compiled`...

Regards.

**Comment by oriolclosa** [comment]
Yes, it seems it has something to do with the version. When I print the package.path and package.cpath variables on the Lua interpreter they print some paths with the number 5.3 on it. However, when Centreon runs the script, those variables don't have the 5.3 but a 5.1 (as this was the previous version the system had). I changed those variables on the same code and it now finds the modules but it fails saying that `undefined symbol: luaL_setfuncsLua` which I believe has something to do with the version (as this wasn't available in 5.1). However when the command `lua -v` is executed by Centreon, it outputs 5.3.

Is there anything else I missed when I updated Lua? I simply compiled the code and changed the binaries in /usr/bin, I've searched "lua" throughout all the system and I haven't been able to locate anything regarding the old 5.1 version.

About the _PATH_ thing, it was just a placeholder for not making the path public, but yes, the broker has the correct one and the script absolutely is found by Centreon.

Thank-you!

**Comment by oriolclosa** [comment]
Sorry for the lateness! I tried to upgrade the library for Centreon to 5.3 but let's say it didn't work, in fact, it stopped running any Lua code. Then I tried to install the modules for 5.1 and surprise, it's now working!

Still, I have a question regarding the method used to parse the data because I think it doesn't cover a bunch of cases. For example you can have the identifier of the metric with spaces if it's inside colons or missing data (we have both cases, I know we shouldn't but...), something like `'CPU Load'=5;80;90;;;`. All I want to know is the output of your function, it's just a dictionary (key and value)?

Thank-you so much!

**Comment by oriolclosa** [comment]
Nevermind it was that and it's working perfectly with our perfdata function, thank-you so much for your help!

**Comment by bouda1** [comment]
OK, I understand better about the version now. You did not compile centreon broker yourself. You installed directly the rpm provided by centreon. And yes it has been compiled with lua5.1.

Happy to see that the stream connector works for you !
