### ISSUE TITLE
(stream) pagerduty-events-apiv2.lua broken near format_event()

### ISSUE THREAD

**Issue by dmagniez** [centreon/centreon-stream-connector-scripts#115]
host critical triggered with check_dummy doesn't generate events.

 We dig this a little bit, and found out that :
we need to disable host_status_dedup

the two first soft state are processed well :
```
Thu Jun 16 00:54:21 2022: INFO: [sc_event:is_host_status_event_duplicated]: host status is not enabled option enable_host_status_dedup is set to: 0
Thu Jun 16 00:54:21 2022: WARNING: [sc_event:is_valid_event_state_type]: event is not in an valid state type. Event state type must be above or equal to 1. Current state type: 0
Thu Jun 16 00:54:21 2022: WARNING: [sc_event:is_valid_host_status_event]: host_id: 3524 is not in a validated downtime, ack or hard/soft state
```

but when check enter in hard state, .lua script is entering "starting format event" function, but does not out.

```
Thu Jun 16 00:56:21 2022: INFO: [sc_flush:get_queues_size]: size of queue for category neb and element: host_status is: 0
Thu Jun 16 00:56:21 2022: INFO: [sc_flush:get_queues_size]: size of queue for category neb and element: service_status is: 0
Thu Jun 16 00:56:21 2022: INFO: [sc_event:is_host_status_event_duplicated]: host status is not enabled option enable_host_status_dedup is set to: 0
Thu Jun 16 00:56:21 2022: INFO: [EventQueue:format_event]: starting format event
Thu Jun 16 00:56:21 2022: INFO: [sc_flush:get_queues_size]: size of queue for category neb and element: host_status is: 0
Thu Jun 16 00:56:21 2022: INFO: [sc_flush:get_queues_size]: size of queue for category neb and element: service_status is: 0
```

with some logger added to the code at every part of the script, we found out the script doesn't pass the line 
`self.format_event[category][element]()`

**Comment by tanguyvda** [comment]
hello,

first of all, thanks for your first analyse, it's going to be quicker to fix :D 
I may have an idea but to confirm it, I need to know your centreon version.

**Comment by dmagniez** [comment]
Centreon 22.04.0
(commit  [8b957a9806](https://github.com/centreon/centreon/tree/8b957a9806))

**Comment by dmagniez** [comment]
for information, we have some word with Simon Bomm on Slack Yesterday

**Comment by tanguyvda** [comment]
we had some major changes between 21.10 and 22.04. I didn't face issues during my test but maybe i've overlooked something. 

i'll do the following today : 
create a passive host 
force a down status on it until it goes hard 
and see what happens

**Comment by tanguyvda** [comment]
just a quick update to let you know that i've reproduced the issue and i've identified the issue. A fix is on its way

**Comment by tanguyvda** [comment]
Okay, i've made the fix, you can apply it manually by editing the 
/usr/share/lua/`<lua_version>`/centreon-stream-connectors-lib/sc_event.lua 

a new release of the stream connectors lib is on its way but will not be available today (may be tomorrow). If you don't want to apply the patch manually, you can just wait and I'll notify you as soon as it is officially released

**Comment by dmagniez** [comment]
Wow amazing, you did a great job, it's working !
I love the reaction time, good explanation, follow up and quick fix !
It was a key function for us, thank you very much !
