### ISSUE TITLE
broker.parse_perfdata function and perfdata not well formatted

### ISSUE THREAD

**Issue by arnaud-michel** [centreon/centreon-stream-connector-scripts#5]
Hello,

There is an issue with broker.parse_perfdata function when perfdata is not well formatted :
[1550162271] error:   lua: error running function `write'/usr/share/centreon-broker/lua/export-warp10.lua:76: storage: error while parsing perfdata << **'events'=;;;0; >>: storage: invalid perfdata format: no numeric value after equal sign**

My workaround to avoid broker retention is this in the lua script :
   local status, pd = pcall(broker.parse_perfdata(d.perfdata))
    if not status then
      broker_log:error(0, "host:service: '" .. d.host_id .. ":" .. d.service_id .. "'")
      return true
    --  pd=
    end

But maybe it would be better to implement an exception directly in broker.parse_perfdata function.

Best Regards

**Comment by bouda1** [comment]
Thank you. This bug is more related to centreon-broker, let's keep it here ! I'll close it when broker will contain the patch.

**Comment by bouda1** [comment]
This is fixed and should be available nos.
