### ISSUE TITLE
TimescaleDB (PostgreSQL) Stream connector

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-stream-connector-scripts#8]
Hi,

How hard would it be to write a TimescaleDB Stream connector script ?
As TimescaleDB is built upon PostgreSQL, writes must be done [using SQL queries](https://docs.timescale.com/using-timescaledb/writing-data).

Thank you for your inputs !

:+1:

**Comment by bouda1** [comment]
Hi,

It depends on what you want to store in this database.
If you only want to store your metrics, you can begin with the warp10 or influxdb streamconnector and adapt queries. It should not be very long to adapt.

You can try, propose your first shot here and I will be able to help you if something goes wrong.

**Comment by CPbN** [comment]
Thank you very much @bouda1 for your response !

I already had a look at the various existing scripts.
The "problem" is that they all connect to remote storage through HTTP.
Whereas TimescaleDB needs a PostgreSQL connection.
So I'm not sure how to proceed here :|

**Comment by bouda1** [comment]
OK, you need a connector for PostgreSQL. If your centreon is on CentOS7, you won't find it directly. You have to install luarocks and then you should be able to install the luasql library. It contains a sublibrary for Postgresql.
Take a look there https://keplerproject.github.io/luasql/

I have already used luasql for Mariadb and it works like a charm !
Good luck!

**Comment by CPbN** [comment]
Thank you again @bouda1.
Perfectly clear now.
I also discovered lua-dbi, which has its CentOS 7 package, and which could do the trick.
Perfect, enough info to work on this !
